// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: assets/v2/assets/eventmessage.proto

package assets

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on EventMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EventMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EventMessage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EventMessageMultiError, or
// nil if none found.
func (m *EventMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *EventMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetEvent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EventMessageValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EventMessageValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEvent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EventMessageValidationError{
				field:  "Event",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAsset()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EventMessageValidationError{
					field:  "Asset",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EventMessageValidationError{
					field:  "Asset",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAsset()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EventMessageValidationError{
				field:  "Asset",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for TenantId

	// no validation rules for FailedReason

	// no validation rules for AssetCreate2Factory

	// no validation rules for EventCreate2Factory

	if len(errors) > 0 {
		return EventMessageMultiError(errors)
	}

	return nil
}

// EventMessageMultiError is an error wrapping multiple validation errors
// returned by EventMessage.ValidateAll() if the designated constraints aren't met.
type EventMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EventMessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EventMessageMultiError) AllErrors() []error { return m }

// EventMessageValidationError is the validation error returned by
// EventMessage.Validate if the designated constraints aren't met.
type EventMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EventMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EventMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EventMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EventMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EventMessageValidationError) ErrorName() string { return "EventMessageValidationError" }

// Error satisfies the builtin error interface
func (e EventMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEventMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EventMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EventMessageValidationError{}
