// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: datatrails-common-api/assets/v2/assets/eventresponsejsonapi.proto

package assets

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on EventResponseJSONAPI with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *EventResponseJSONAPI) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EventResponseJSONAPI with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EventResponseJSONAPIMultiError, or nil if none found.
func (m *EventResponseJSONAPI) ValidateAll() error {
	return m.validate(true)
}

func (m *EventResponseJSONAPI) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Identity

	// no validation rules for AssetIdentity

	// no validation rules for EventAttributes

	// no validation rules for AssetAttributes

	// no validation rules for Operation

	// no validation rules for Behaviour

	// no validation rules for TimestampDeclared

	// no validation rules for TimestampAccepted

	// no validation rules for TimestampCommitted

	if all {
		switch v := interface{}(m.GetPrincipalDeclared()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EventResponseJSONAPIValidationError{
					field:  "PrincipalDeclared",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EventResponseJSONAPIValidationError{
					field:  "PrincipalDeclared",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPrincipalDeclared()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EventResponseJSONAPIValidationError{
				field:  "PrincipalDeclared",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetPrincipalAccepted()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, EventResponseJSONAPIValidationError{
					field:  "PrincipalAccepted",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, EventResponseJSONAPIValidationError{
					field:  "PrincipalAccepted",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPrincipalAccepted()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return EventResponseJSONAPIValidationError{
				field:  "PrincipalAccepted",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ConfirmationStatus

	// no validation rules for TransactionId

	// no validation rules for BlockNumber

	// no validation rules for TransactionIndex

	// no validation rules for From

	// no validation rules for TenantIdentity

	switch v := m.ProofDetails.(type) {
	case *EventResponseJSONAPI_MerklelogEntry:
		if v == nil {
			err := EventResponseJSONAPIValidationError{
				field:  "ProofDetails",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetMerklelogEntry()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, EventResponseJSONAPIValidationError{
						field:  "MerklelogEntry",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, EventResponseJSONAPIValidationError{
						field:  "MerklelogEntry",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetMerklelogEntry()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return EventResponseJSONAPIValidationError{
					field:  "MerklelogEntry",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return EventResponseJSONAPIMultiError(errors)
	}

	return nil
}

// EventResponseJSONAPIMultiError is an error wrapping multiple validation
// errors returned by EventResponseJSONAPI.ValidateAll() if the designated
// constraints aren't met.
type EventResponseJSONAPIMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EventResponseJSONAPIMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EventResponseJSONAPIMultiError) AllErrors() []error { return m }

// EventResponseJSONAPIValidationError is the validation error returned by
// EventResponseJSONAPI.Validate if the designated constraints aren't met.
type EventResponseJSONAPIValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EventResponseJSONAPIValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EventResponseJSONAPIValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EventResponseJSONAPIValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EventResponseJSONAPIValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EventResponseJSONAPIValidationError) ErrorName() string {
	return "EventResponseJSONAPIValidationError"
}

// Error satisfies the builtin error interface
func (e EventResponseJSONAPIValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEventResponseJSONAPI.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EventResponseJSONAPIValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EventResponseJSONAPIValidationError{}
