// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: datatrails-common-api/assets/v2/assets/getasset.proto

package assets

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _getasset_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on GetAssetRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetAssetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAssetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAssetRequestMultiError, or nil if none found.
func (m *GetAssetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAssetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUuid()); err != nil {
		err = GetAssetRequestValidationError{
			field:  "Uuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetAtTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetAssetRequestValidationError{
					field:  "AtTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetAssetRequestValidationError{
					field:  "AtTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAtTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetAssetRequestValidationError{
				field:  "AtTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetAssetRequestMultiError(errors)
	}

	return nil
}

func (m *GetAssetRequest) _validateUuid(uuid string) error {
	if matched := _getasset_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetAssetRequestMultiError is an error wrapping multiple validation errors
// returned by GetAssetRequest.ValidateAll() if the designated constraints
// aren't met.
type GetAssetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAssetRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAssetRequestMultiError) AllErrors() []error { return m }

// GetAssetRequestValidationError is the validation error returned by
// GetAssetRequest.Validate if the designated constraints aren't met.
type GetAssetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAssetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAssetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAssetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAssetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAssetRequestValidationError) ErrorName() string { return "GetAssetRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetAssetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAssetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAssetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAssetRequestValidationError{}

// Validate checks the field values on GetAssetPublicURLRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAssetPublicURLRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAssetPublicURLRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAssetPublicURLRequestMultiError, or nil if none found.
func (m *GetAssetPublicURLRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAssetPublicURLRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUuid()); err != nil {
		err = GetAssetPublicURLRequestValidationError{
			field:  "Uuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetAssetPublicURLRequestMultiError(errors)
	}

	return nil
}

func (m *GetAssetPublicURLRequest) _validateUuid(uuid string) error {
	if matched := _getasset_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetAssetPublicURLRequestMultiError is an error wrapping multiple validation
// errors returned by GetAssetPublicURLRequest.ValidateAll() if the designated
// constraints aren't met.
type GetAssetPublicURLRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAssetPublicURLRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAssetPublicURLRequestMultiError) AllErrors() []error { return m }

// GetAssetPublicURLRequestValidationError is the validation error returned by
// GetAssetPublicURLRequest.Validate if the designated constraints aren't met.
type GetAssetPublicURLRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAssetPublicURLRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAssetPublicURLRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAssetPublicURLRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAssetPublicURLRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAssetPublicURLRequestValidationError) ErrorName() string {
	return "GetAssetPublicURLRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetAssetPublicURLRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAssetPublicURLRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAssetPublicURLRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAssetPublicURLRequestValidationError{}
