// Maintainers, please refer to the style guide here:
//     https://developers.google.com/protocol-buffers/docs/style

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: datatrails-common-api/assets/v2/assets/merklelogentry.proto

package assets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MerkeLogCommit provides the log entry details for a single mmr leaf.
type MerkleLogCommit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The mmr index
	Index uint64 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	// The mmr *leaf* index
	LeafIndex uint64 `protobuf:"varint,4,opt,name=leaf_index,json=leafIndex,proto3" json:"leaf_index,omitempty"` // TBD: this may be redundant.
	// time ordered and strictly unique per tenant. system wide
	// unique with very reasonable operational assumptions.
	Idtimestamp uint64 `protobuf:"fixed64,5,opt,name=idtimestamp,proto3" json:"idtimestamp,omitempty"`
}

func (x *MerkleLogCommit) Reset() {
	*x = MerkleLogCommit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerkleLogCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleLogCommit) ProtoMessage() {}

func (x *MerkleLogCommit) ProtoReflect() protoreflect.Message {
	mi := &file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleLogCommit.ProtoReflect.Descriptor instead.
func (*MerkleLogCommit) Descriptor() ([]byte, []int) {
	return file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_rawDescGZIP(), []int{0}
}

func (x *MerkleLogCommit) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *MerkleLogCommit) GetLeafIndex() uint64 {
	if x != nil {
		return x.LeafIndex
	}
	return 0
}

func (x *MerkleLogCommit) GetIdtimestamp() uint64 {
	if x != nil {
		return x.Idtimestamp
	}
	return 0
}

// The message sent from forestrie to avid notifying that the corresponding
// event is commited to the tenants log.
type MerkleLogCommitMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The tenant identity and the event identity for the committed event.
	TenantIdentity string `protobuf:"bytes,1,opt,name=tenant_identity,json=tenantIdentity,proto3" json:"tenant_identity,omitempty"`
	EventIdentity  string `protobuf:"bytes,2,opt,name=event_identity,json=eventIdentity,proto3" json:"event_identity,omitempty"`
	// The time portion of idtimestamp that contributed to the hash of the event
	// (the idtimestamp is _also_ included.
	// This must be copied into event.timestamp_committed when the saas db is updated
	Timestamp  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LogVersion uint32                 `protobuf:"varint,3,opt,name=log_version,json=logVersion,proto3" json:"log_version,omitempty"`
	LogEpoch   uint32                 `protobuf:"varint,4,opt,name=log_epoch,json=logEpoch,proto3" json:"log_epoch,omitempty"`
	Commit     *MerkleLogCommit       `protobuf:"bytes,5,opt,name=commit,proto3" json:"commit,omitempty"`
}

func (x *MerkleLogCommitMessage) Reset() {
	*x = MerkleLogCommitMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerkleLogCommitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleLogCommitMessage) ProtoMessage() {}

func (x *MerkleLogCommitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleLogCommitMessage.ProtoReflect.Descriptor instead.
func (*MerkleLogCommitMessage) Descriptor() ([]byte, []int) {
	return file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_rawDescGZIP(), []int{1}
}

func (x *MerkleLogCommitMessage) GetTenantIdentity() string {
	if x != nil {
		return x.TenantIdentity
	}
	return ""
}

func (x *MerkleLogCommitMessage) GetEventIdentity() string {
	if x != nil {
		return x.EventIdentity
	}
	return ""
}

func (x *MerkleLogCommitMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MerkleLogCommitMessage) GetLogVersion() uint32 {
	if x != nil {
		return x.LogVersion
	}
	return 0
}

func (x *MerkleLogCommitMessage) GetLogEpoch() uint32 {
	if x != nil {
		return x.LogEpoch
	}
	return 0
}

func (x *MerkleLogCommitMessage) GetCommit() *MerkleLogCommit {
	if x != nil {
		return x.Commit
	}
	return nil
}

// The details stored in the SaaS db for a proof mech MERKLE_LOG commitment
type MerkleLogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The tenant log version and epoch when the log entry was created.
	LogVersion uint32 `protobuf:"varint,1,opt,name=log_version,json=logVersion,proto3" json:"log_version,omitempty"`
	LogEpoch   uint32 `protobuf:"varint,2,opt,name=log_epoch,json=logEpoch,proto3" json:"log_epoch,omitempty"`
	// Event trust level commited fields
	Commit *MerkleLogCommit `protobuf:"bytes,3,opt,name=commit,proto3" json:"commit,omitempty"`
}

func (x *MerkleLogEntry) Reset() {
	*x = MerkleLogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerkleLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleLogEntry) ProtoMessage() {}

func (x *MerkleLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleLogEntry.ProtoReflect.Descriptor instead.
func (*MerkleLogEntry) Descriptor() ([]byte, []int) {
	return file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_rawDescGZIP(), []int{2}
}

func (x *MerkleLogEntry) GetLogVersion() uint32 {
	if x != nil {
		return x.LogVersion
	}
	return 0
}

func (x *MerkleLogEntry) GetLogEpoch() uint32 {
	if x != nil {
		return x.LogEpoch
	}
	return 0
}

func (x *MerkleLogEntry) GetCommit() *MerkleLogCommit {
	if x != nil {
		return x.Commit
	}
	return nil
}

var File_datatrails_common_api_assets_v2_assets_merklelogentry_proto protoreflect.FileDescriptor

var file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_rawDesc = []byte{
	0x0a, 0x3b, 0x64, 0x61, 0x74, 0x61, 0x74, 0x72, 0x61, 0x69, 0x6c, 0x73, 0x2d, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x76,
	0x32, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x6c,
	0x6f, 0x67, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61,
	0x72, 0x63, 0x68, 0x69, 0x76, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x32, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x0f,
	0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x4c, 0x6f, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x65, 0x61, 0x66, 0x5f, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6c, 0x65, 0x61, 0x66, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x64, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x06, 0x52, 0x0b, 0x69, 0x64, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x97, 0x02, 0x0a, 0x16, 0x4d, 0x65, 0x72, 0x6b, 0x6c,
	0x65, 0x4c, 0x6f, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x65, 0x6e, 0x61,
	0x6e, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x6c,
	0x6f, 0x67, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x6c, 0x6f, 0x67, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09,
	0x6c, 0x6f, 0x67, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x6c, 0x6f, 0x67, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x35, 0x0a, 0x06, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x72, 0x63, 0x68,
	0x69, 0x76, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x4c,
	0x6f, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x22, 0x85, 0x01, 0x0a, 0x0e, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x4c, 0x6f, 0x67, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x6f, 0x67, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6c, 0x6f, 0x67, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x5f, 0x65, 0x70, 0x6f, 0x63,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x45, 0x70, 0x6f, 0x63,
	0x68, 0x12, 0x35, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x32,
	0x2e, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x4c, 0x6f, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x42, 0x4c, 0x5a, 0x4a, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x74, 0x72, 0x61, 0x69, 0x6c,
	0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x74, 0x72, 0x61, 0x69, 0x6c, 0x73, 0x2d,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x65, 0x6e, 0x2f, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x76, 0x32, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x3b,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_rawDescOnce sync.Once
	file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_rawDescData = file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_rawDesc
)

func file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_rawDescGZIP() []byte {
	file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_rawDescOnce.Do(func() {
		file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_rawDescData = protoimpl.X.CompressGZIP(file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_rawDescData)
	})
	return file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_rawDescData
}

var file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_goTypes = []interface{}{
	(*MerkleLogCommit)(nil),        // 0: archivist.v2.MerkleLogCommit
	(*MerkleLogCommitMessage)(nil), // 1: archivist.v2.MerkleLogCommitMessage
	(*MerkleLogEntry)(nil),         // 2: archivist.v2.MerkleLogEntry
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
}
var file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_depIdxs = []int32{
	3, // 0: archivist.v2.MerkleLogCommitMessage.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: archivist.v2.MerkleLogCommitMessage.commit:type_name -> archivist.v2.MerkleLogCommit
	0, // 2: archivist.v2.MerkleLogEntry.commit:type_name -> archivist.v2.MerkleLogCommit
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_init() }
func file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_init() {
	if File_datatrails_common_api_assets_v2_assets_merklelogentry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerkleLogCommit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerkleLogCommitMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerkleLogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_goTypes,
		DependencyIndexes: file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_depIdxs,
		MessageInfos:      file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_msgTypes,
	}.Build()
	File_datatrails_common_api_assets_v2_assets_merklelogentry_proto = out.File
	file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_rawDesc = nil
	file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_goTypes = nil
	file_datatrails_common_api_assets_v2_assets_merklelogentry_proto_depIdxs = nil
}
