// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: quorumnetwork/v1/quorumnetwork/quorumnetwork.proto

package quorumnetwork

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on QuorumNetwork with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *QuorumNetwork) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QuorumNetwork with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in QuorumNetworkMultiError, or
// nil if none found.
func (m *QuorumNetwork) ValidateAll() error {
	return m.validate(true)
}

func (m *QuorumNetwork) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetNodeAddress()); l < 1 || l > 1024 {
		err := QuorumNetworkValidationError{
			field:  "NodeAddress",
			reason: "value length must be between 1 and 1024 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetTesseraAddress()); l < 1 || l > 1024 {
		err := QuorumNetworkValidationError{
			field:  "TesseraAddress",
			reason: "value length must be between 1 and 1024 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetTesseraKey()); l < 1 || l > 1024 {
		err := QuorumNetworkValidationError{
			field:  "TesseraKey",
			reason: "value length must be between 1 and 1024 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetTopic()); l < 1 || l > 1024 {
		err := QuorumNetworkValidationError{
			field:  "Topic",
			reason: "value length must be between 1 and 1024 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for IsPrivate

	if len(errors) > 0 {
		return QuorumNetworkMultiError(errors)
	}

	return nil
}

// QuorumNetworkMultiError is an error wrapping multiple validation errors
// returned by QuorumNetwork.ValidateAll() if the designated constraints
// aren't met.
type QuorumNetworkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QuorumNetworkMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QuorumNetworkMultiError) AllErrors() []error { return m }

// QuorumNetworkValidationError is the validation error returned by
// QuorumNetwork.Validate if the designated constraints aren't met.
type QuorumNetworkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QuorumNetworkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QuorumNetworkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QuorumNetworkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QuorumNetworkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QuorumNetworkValidationError) ErrorName() string { return "QuorumNetworkValidationError" }

// Error satisfies the builtin error interface
func (e QuorumNetworkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQuorumNetwork.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QuorumNetworkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QuorumNetworkValidationError{}
